-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/WikiRAG/db/wikirag_history.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wikirag_history (
  wrh_namespace INTEGER NOT NULL,
  wrh_title BLOB NOT NULL,
  wrh_pipeline BLOB NOT NULL,
  wrh_status BLOB NOT NULL,
  wrh_error_message CLOB DEFAULT NULL,
  wrh_timestamp BLOB NOT NULL,
  PRIMARY KEY(
    wrh_namespace, wrh_title, wrh_pipeline
  )
);
