-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/WikiRAG/db/wikirag_history.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wikirag_history (
  wrh_namespace INT NOT NULL,
  wrh_title VARBINARY(255) NOT NULL,
  wrh_pipeline VARBINARY(255) NOT NULL,
  wrh_status VARBINARY(20) NOT NULL,
  wrh_error_message LONGTEXT DEFAULT NULL,
  wrh_timestamp BINARY(14) NOT NULL,
  PRIMARY KEY(
    wrh_namespace, wrh_title, wrh_pipeline
  )
) /*$wgDBTableOptions*/;
