-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/WikiRAG/db/wikirag_queue.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wikirag_queue (
  wrq_namespace INT UNSIGNED NOT NULL,
  wrq_title VARBINARY(255) NOT NULL,
  wrq_pipeline VARBINARY(255) NOT NULL,
  wrq_scheduled_at BINARY(14) NOT NULL,
  PRIMARY KEY(
    wrq_namespace, wrq_title, wrq_pipeline
  )
) /*$wgDBTableOptions*/;
