-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/WikiRAG/db/wikirag_history.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE wikirag_history (
  wrh_namespace INT NOT NULL,
  wrh_title TEXT NOT NULL,
  wrh_pipeline TEXT NOT NULL,
  wrh_status TEXT NOT NULL,
  wrh_error_message TEXT DEFAULT NULL,
  wrh_timestamp TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(
    wrh_namespace, wrh_title, wrh_pipeline
  )
);
