-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/WikiRAG/db/wikirag_queue.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE wikirag_queue (
  wrq_namespace INT NOT NULL,
  wrq_title TEXT NOT NULL,
  wrq_pipeline TEXT NOT NULL,
  wrq_scheduled_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(
    wrq_namespace, wrq_title, wrq_pipeline
  )
);
